// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sprisa/west/westport/db/ent/device"
	"github.com/sprisa/west/westport/db/ent/host"
	"github.com/sprisa/west/westport/db/ent/predicate"
	"github.com/sprisa/west/westport/db/helpers"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *DeviceUpdate) SetUpdatedTime(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdate) SetName(v string) *DeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLeasedAccessToken sets the "leased_access_token" field.
func (_u *DeviceUpdate) SetLeasedAccessToken(v string) *DeviceUpdate {
	_u.mutation.SetLeasedAccessToken(v)
	return _u
}

// SetNillableLeasedAccessToken sets the "leased_access_token" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLeasedAccessToken(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetLeasedAccessToken(*v)
	}
	return _u
}

// ClearLeasedAccessToken clears the value of the "leased_access_token" field.
func (_u *DeviceUpdate) ClearLeasedAccessToken() *DeviceUpdate {
	_u.mutation.ClearLeasedAccessToken()
	return _u
}

// SetToken sets the "token" field.
func (_u *DeviceUpdate) SetToken(v helpers.EncryptedBytes) *DeviceUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetHostID sets the "host" edge to the Host entity by ID.
func (_u *DeviceUpdate) SetHostID(id int) *DeviceUpdate {
	_u.mutation.SetHostID(id)
	return _u
}

// SetHost sets the "host" edge to the Host entity.
func (_u *DeviceUpdate) SetHost(v *Host) *DeviceUpdate {
	return _u.SetHostID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the Host entity.
func (_u *DeviceUpdate) ClearHost() *DeviceUpdate {
	_u.mutation.ClearHost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := device.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.host"`)
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(device.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeasedAccessToken(); ok {
		_spec.SetField(device.FieldLeasedAccessToken, field.TypeString, value)
	}
	if _u.mutation.LeasedAccessTokenCleared() {
		_spec.ClearField(device.FieldLeasedAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(device.FieldToken, field.TypeBytes, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   device.HostTable,
			Columns: []string{device.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   device.HostTable,
			Columns: []string{device.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *DeviceUpdateOne) SetUpdatedTime(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdateOne) SetName(v string) *DeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLeasedAccessToken sets the "leased_access_token" field.
func (_u *DeviceUpdateOne) SetLeasedAccessToken(v string) *DeviceUpdateOne {
	_u.mutation.SetLeasedAccessToken(v)
	return _u
}

// SetNillableLeasedAccessToken sets the "leased_access_token" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLeasedAccessToken(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetLeasedAccessToken(*v)
	}
	return _u
}

// ClearLeasedAccessToken clears the value of the "leased_access_token" field.
func (_u *DeviceUpdateOne) ClearLeasedAccessToken() *DeviceUpdateOne {
	_u.mutation.ClearLeasedAccessToken()
	return _u
}

// SetToken sets the "token" field.
func (_u *DeviceUpdateOne) SetToken(v helpers.EncryptedBytes) *DeviceUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetHostID sets the "host" edge to the Host entity by ID.
func (_u *DeviceUpdateOne) SetHostID(id int) *DeviceUpdateOne {
	_u.mutation.SetHostID(id)
	return _u
}

// SetHost sets the "host" edge to the Host entity.
func (_u *DeviceUpdateOne) SetHost(v *Host) *DeviceUpdateOne {
	return _u.SetHostID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the Host entity.
func (_u *DeviceUpdateOne) ClearHost() *DeviceUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := device.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.host"`)
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(device.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeasedAccessToken(); ok {
		_spec.SetField(device.FieldLeasedAccessToken, field.TypeString, value)
	}
	if _u.mutation.LeasedAccessTokenCleared() {
		_spec.ClearField(device.FieldLeasedAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(device.FieldToken, field.TypeBytes, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   device.HostTable,
			Columns: []string{device.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   device.HostTable,
			Columns: []string{device.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
