// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/sprisa/west/westport/db/ent/device"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// DeviceEdge is the edge representation of Device.
type DeviceEdge struct {
	Node   *Device `json:"node"`
	Cursor Cursor  `json:"cursor"`
}

// DeviceConnection is the connection containing edges to Device.
type DeviceConnection struct {
	Edges      []*DeviceEdge `json:"edges"`
	PageInfo   PageInfo      `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

func (c *DeviceConnection) build(nodes []*Device, pager *devicePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Device
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Device {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Device {
			return nodes[i]
		}
	}
	c.Edges = make([]*DeviceEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &DeviceEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// DevicePaginateOption enables pagination customization.
type DevicePaginateOption func(*devicePager) error

// WithDeviceOrder configures pagination ordering.
func WithDeviceOrder(order *DeviceOrder) DevicePaginateOption {
	if order == nil {
		order = DefaultDeviceOrder
	}
	o := *order
	return func(pager *devicePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultDeviceOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithDeviceFilter configures pagination filter.
func WithDeviceFilter(filter func(*DeviceQuery) (*DeviceQuery, error)) DevicePaginateOption {
	return func(pager *devicePager) error {
		if filter == nil {
			return errors.New("DeviceQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type devicePager struct {
	reverse bool
	order   *DeviceOrder
	filter  func(*DeviceQuery) (*DeviceQuery, error)
}

func newDevicePager(opts []DevicePaginateOption, reverse bool) (*devicePager, error) {
	pager := &devicePager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultDeviceOrder
	}
	return pager, nil
}

func (p *devicePager) applyFilter(query *DeviceQuery) (*DeviceQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *devicePager) toCursor(_m *Device) Cursor {
	return p.order.Field.toCursor(_m)
}

func (p *devicePager) applyCursors(query *DeviceQuery, after, before *Cursor) (*DeviceQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultDeviceOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *devicePager) applyOrder(query *DeviceQuery) *DeviceQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultDeviceOrder.Field {
		query = query.Order(DefaultDeviceOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *devicePager) orderExpr(query *DeviceQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultDeviceOrder.Field {
			b.Comma().Ident(DefaultDeviceOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Device.
func (_m *DeviceQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...DevicePaginateOption,
) (*DeviceConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newDevicePager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if _m, err = pager.applyFilter(_m); err != nil {
		return nil, err
	}
	conn := &DeviceConnection{Edges: []*DeviceEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := _m.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if _m, err = pager.applyCursors(_m, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		_m.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := _m.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	_m = pager.applyOrder(_m)
	nodes, err := _m.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// DeviceOrderField defines the ordering field of Device.
type DeviceOrderField struct {
	// Value extracts the ordering value from the given Device.
	Value    func(*Device) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) device.OrderOption
	toCursor func(*Device) Cursor
}

// DeviceOrder defines the ordering of Device.
type DeviceOrder struct {
	Direction OrderDirection    `json:"direction"`
	Field     *DeviceOrderField `json:"field"`
}

// DefaultDeviceOrder is the default ordering of Device.
var DefaultDeviceOrder = &DeviceOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &DeviceOrderField{
		Value: func(_m *Device) (ent.Value, error) {
			return _m.ID, nil
		},
		column: device.FieldID,
		toTerm: device.ByID,
		toCursor: func(_m *Device) Cursor {
			return Cursor{ID: _m.ID}
		},
	},
}

// ToEdge converts Device into DeviceEdge.
func (_m *Device) ToEdge(order *DeviceOrder) *DeviceEdge {
	if order == nil {
		order = DefaultDeviceOrder
	}
	return &DeviceEdge{
		Node:   _m,
		Cursor: order.Field.toCursor(_m),
	}
}
