// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sprisa/west/util/ipconv"
	"github.com/sprisa/west/westport/db/ent/host"
	"github.com/sprisa/west/westport/db/ent/lighthouse"
	"github.com/sprisa/west/westport/db/helpers"
)

// LighthouseCreate is the builder for creating a Lighthouse entity.
type LighthouseCreate struct {
	config
	mutation *LighthouseMutation
	hooks    []Hook
}

// SetCreatedTime sets the "created_time" field.
func (_c *LighthouseCreate) SetCreatedTime(v time.Time) *LighthouseCreate {
	_c.mutation.SetCreatedTime(v)
	return _c
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_c *LighthouseCreate) SetNillableCreatedTime(v *time.Time) *LighthouseCreate {
	if v != nil {
		_c.SetCreatedTime(*v)
	}
	return _c
}

// SetUpdatedTime sets the "updated_time" field.
func (_c *LighthouseCreate) SetUpdatedTime(v time.Time) *LighthouseCreate {
	_c.mutation.SetUpdatedTime(v)
	return _c
}

// SetNillableUpdatedTime sets the "updated_time" field if the given value is not nil.
func (_c *LighthouseCreate) SetNillableUpdatedTime(v *time.Time) *LighthouseCreate {
	if v != nil {
		_c.SetUpdatedTime(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *LighthouseCreate) SetIP(v ipconv.IP) *LighthouseCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *LighthouseCreate) SetEndpoint(v string) *LighthouseCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetCertificate sets the "certificate" field.
func (_c *LighthouseCreate) SetCertificate(v helpers.EncryptedBytes) *LighthouseCreate {
	_c.mutation.SetCertificate(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *LighthouseCreate) SetKey(v helpers.EncryptedBytes) *LighthouseCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetAPIEndpoint sets the "api_endpoint" field.
func (_c *LighthouseCreate) SetAPIEndpoint(v string) *LighthouseCreate {
	_c.mutation.SetAPIEndpoint(v)
	return _c
}

// SetHostID sets the "host" edge to the Host entity by ID.
func (_c *LighthouseCreate) SetHostID(id int) *LighthouseCreate {
	_c.mutation.SetHostID(id)
	return _c
}

// SetHost sets the "host" edge to the Host entity.
func (_c *LighthouseCreate) SetHost(v *Host) *LighthouseCreate {
	return _c.SetHostID(v.ID)
}

// Mutation returns the LighthouseMutation object of the builder.
func (_c *LighthouseCreate) Mutation() *LighthouseMutation {
	return _c.mutation
}

// Save creates the Lighthouse in the database.
func (_c *LighthouseCreate) Save(ctx context.Context) (*Lighthouse, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LighthouseCreate) SaveX(ctx context.Context) *Lighthouse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LighthouseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LighthouseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LighthouseCreate) defaults() {
	if _, ok := _c.mutation.CreatedTime(); !ok {
		v := lighthouse.DefaultCreatedTime()
		_c.mutation.SetCreatedTime(v)
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		v := lighthouse.DefaultUpdatedTime()
		_c.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LighthouseCreate) check() error {
	if _, ok := _c.mutation.CreatedTime(); !ok {
		return &ValidationError{Name: "created_time", err: errors.New(`ent: missing required field "Lighthouse.created_time"`)}
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		return &ValidationError{Name: "updated_time", err: errors.New(`ent: missing required field "Lighthouse.updated_time"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Lighthouse.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := lighthouse.IPValidator(uint32(v)); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Lighthouse.ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Endpoint(); !ok {
		return &ValidationError{Name: "endpoint", err: errors.New(`ent: missing required field "Lighthouse.endpoint"`)}
	}
	if _, ok := _c.mutation.Certificate(); !ok {
		return &ValidationError{Name: "certificate", err: errors.New(`ent: missing required field "Lighthouse.certificate"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Lighthouse.key"`)}
	}
	if _, ok := _c.mutation.APIEndpoint(); !ok {
		return &ValidationError{Name: "api_endpoint", err: errors.New(`ent: missing required field "Lighthouse.api_endpoint"`)}
	}
	if len(_c.mutation.HostIDs()) == 0 {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required edge "Lighthouse.host"`)}
	}
	return nil
}

func (_c *LighthouseCreate) sqlSave(ctx context.Context) (*Lighthouse, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LighthouseCreate) createSpec() (*Lighthouse, *sqlgraph.CreateSpec) {
	var (
		_node = &Lighthouse{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lighthouse.Table, sqlgraph.NewFieldSpec(lighthouse.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedTime(); ok {
		_spec.SetField(lighthouse.FieldCreatedTime, field.TypeTime, value)
		_node.CreatedTime = value
	}
	if value, ok := _c.mutation.UpdatedTime(); ok {
		_spec.SetField(lighthouse.FieldUpdatedTime, field.TypeTime, value)
		_node.UpdatedTime = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(lighthouse.FieldIP, field.TypeUint32, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(lighthouse.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Certificate(); ok {
		_spec.SetField(lighthouse.FieldCertificate, field.TypeBytes, value)
		_node.Certificate = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(lighthouse.FieldKey, field.TypeBytes, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.APIEndpoint(); ok {
		_spec.SetField(lighthouse.FieldAPIEndpoint, field.TypeString, value)
		_node.APIEndpoint = value
	}
	if nodes := _c.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lighthouse.HostTable,
			Columns: []string{lighthouse.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.lighthouse_host = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LighthouseCreateBulk is the builder for creating many Lighthouse entities in bulk.
type LighthouseCreateBulk struct {
	config
	err      error
	builders []*LighthouseCreate
}

// Save creates the Lighthouse entities in the database.
func (_c *LighthouseCreateBulk) Save(ctx context.Context) ([]*Lighthouse, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Lighthouse, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LighthouseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LighthouseCreateBulk) SaveX(ctx context.Context) []*Lighthouse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LighthouseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LighthouseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
