// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sprisa/west/westport/db/ent/host"
	"github.com/sprisa/west/westport/db/ent/lighthouse"
	"github.com/sprisa/west/westport/db/ent/predicate"
	"github.com/sprisa/west/westport/db/helpers"
)

// LighthouseUpdate is the builder for updating Lighthouse entities.
type LighthouseUpdate struct {
	config
	hooks    []Hook
	mutation *LighthouseMutation
}

// Where appends a list predicates to the LighthouseUpdate builder.
func (_u *LighthouseUpdate) Where(ps ...predicate.Lighthouse) *LighthouseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *LighthouseUpdate) SetUpdatedTime(v time.Time) *LighthouseUpdate {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *LighthouseUpdate) SetEndpoint(v string) *LighthouseUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *LighthouseUpdate) SetNillableEndpoint(v *string) *LighthouseUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetCertificate sets the "certificate" field.
func (_u *LighthouseUpdate) SetCertificate(v helpers.EncryptedBytes) *LighthouseUpdate {
	_u.mutation.SetCertificate(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *LighthouseUpdate) SetKey(v helpers.EncryptedBytes) *LighthouseUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetAPIEndpoint sets the "api_endpoint" field.
func (_u *LighthouseUpdate) SetAPIEndpoint(v string) *LighthouseUpdate {
	_u.mutation.SetAPIEndpoint(v)
	return _u
}

// SetNillableAPIEndpoint sets the "api_endpoint" field if the given value is not nil.
func (_u *LighthouseUpdate) SetNillableAPIEndpoint(v *string) *LighthouseUpdate {
	if v != nil {
		_u.SetAPIEndpoint(*v)
	}
	return _u
}

// SetHostID sets the "host" edge to the Host entity by ID.
func (_u *LighthouseUpdate) SetHostID(id int) *LighthouseUpdate {
	_u.mutation.SetHostID(id)
	return _u
}

// SetHost sets the "host" edge to the Host entity.
func (_u *LighthouseUpdate) SetHost(v *Host) *LighthouseUpdate {
	return _u.SetHostID(v.ID)
}

// Mutation returns the LighthouseMutation object of the builder.
func (_u *LighthouseUpdate) Mutation() *LighthouseMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the Host entity.
func (_u *LighthouseUpdate) ClearHost() *LighthouseUpdate {
	_u.mutation.ClearHost()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LighthouseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LighthouseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LighthouseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LighthouseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LighthouseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := lighthouse.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LighthouseUpdate) check() error {
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lighthouse.host"`)
	}
	return nil
}

func (_u *LighthouseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lighthouse.Table, lighthouse.Columns, sqlgraph.NewFieldSpec(lighthouse.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(lighthouse.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(lighthouse.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Certificate(); ok {
		_spec.SetField(lighthouse.FieldCertificate, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(lighthouse.FieldKey, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.APIEndpoint(); ok {
		_spec.SetField(lighthouse.FieldAPIEndpoint, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lighthouse.HostTable,
			Columns: []string{lighthouse.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lighthouse.HostTable,
			Columns: []string{lighthouse.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lighthouse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LighthouseUpdateOne is the builder for updating a single Lighthouse entity.
type LighthouseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LighthouseMutation
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *LighthouseUpdateOne) SetUpdatedTime(v time.Time) *LighthouseUpdateOne {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *LighthouseUpdateOne) SetEndpoint(v string) *LighthouseUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *LighthouseUpdateOne) SetNillableEndpoint(v *string) *LighthouseUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetCertificate sets the "certificate" field.
func (_u *LighthouseUpdateOne) SetCertificate(v helpers.EncryptedBytes) *LighthouseUpdateOne {
	_u.mutation.SetCertificate(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *LighthouseUpdateOne) SetKey(v helpers.EncryptedBytes) *LighthouseUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetAPIEndpoint sets the "api_endpoint" field.
func (_u *LighthouseUpdateOne) SetAPIEndpoint(v string) *LighthouseUpdateOne {
	_u.mutation.SetAPIEndpoint(v)
	return _u
}

// SetNillableAPIEndpoint sets the "api_endpoint" field if the given value is not nil.
func (_u *LighthouseUpdateOne) SetNillableAPIEndpoint(v *string) *LighthouseUpdateOne {
	if v != nil {
		_u.SetAPIEndpoint(*v)
	}
	return _u
}

// SetHostID sets the "host" edge to the Host entity by ID.
func (_u *LighthouseUpdateOne) SetHostID(id int) *LighthouseUpdateOne {
	_u.mutation.SetHostID(id)
	return _u
}

// SetHost sets the "host" edge to the Host entity.
func (_u *LighthouseUpdateOne) SetHost(v *Host) *LighthouseUpdateOne {
	return _u.SetHostID(v.ID)
}

// Mutation returns the LighthouseMutation object of the builder.
func (_u *LighthouseUpdateOne) Mutation() *LighthouseMutation {
	return _u.mutation
}

// ClearHost clears the "host" edge to the Host entity.
func (_u *LighthouseUpdateOne) ClearHost() *LighthouseUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// Where appends a list predicates to the LighthouseUpdate builder.
func (_u *LighthouseUpdateOne) Where(ps ...predicate.Lighthouse) *LighthouseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LighthouseUpdateOne) Select(field string, fields ...string) *LighthouseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Lighthouse entity.
func (_u *LighthouseUpdateOne) Save(ctx context.Context) (*Lighthouse, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LighthouseUpdateOne) SaveX(ctx context.Context) *Lighthouse {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LighthouseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LighthouseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LighthouseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := lighthouse.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LighthouseUpdateOne) check() error {
	if _u.mutation.HostCleared() && len(_u.mutation.HostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Lighthouse.host"`)
	}
	return nil
}

func (_u *LighthouseUpdateOne) sqlSave(ctx context.Context) (_node *Lighthouse, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lighthouse.Table, lighthouse.Columns, sqlgraph.NewFieldSpec(lighthouse.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lighthouse.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lighthouse.FieldID)
		for _, f := range fields {
			if !lighthouse.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lighthouse.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(lighthouse.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(lighthouse.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Certificate(); ok {
		_spec.SetField(lighthouse.FieldCertificate, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(lighthouse.FieldKey, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.APIEndpoint(); ok {
		_spec.SetField(lighthouse.FieldAPIEndpoint, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lighthouse.HostTable,
			Columns: []string{lighthouse.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   lighthouse.HostTable,
			Columns: []string{lighthouse.HostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(host.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Lighthouse{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lighthouse.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
