// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sprisa/west/util/ipconv"
	"github.com/sprisa/west/westport/db/ent/host"
	"github.com/sprisa/west/westport/db/ent/lighthouse"
	"github.com/sprisa/west/westport/db/helpers"
)

// Lighthouse is the model entity for the Lighthouse schema.
type Lighthouse struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Time ent was created
	CreatedTime time.Time `json:"created_time,omitempty"`
	// Time ent was updated
	UpdatedTime time.Time `json:"updated_time,omitempty"`
	// Nebula overlay IPv4 of the lighthouse
	IP ipconv.IP `json:"ip,omitempty"`
	// Public Nebula host and UDP port
	Endpoint string `json:"endpoint,omitempty"`
	// Certificate holds the value of the "certificate" field.
	Certificate helpers.EncryptedBytes `json:"-"`
	// Key holds the value of the "key" field.
	Key helpers.EncryptedBytes `json:"-"`
	// Physical API host:port for this node
	APIEndpoint string `json:"api_endpoint,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LighthouseQuery when eager-loading is set.
	Edges           LighthouseEdges `json:"edges"`
	lighthouse_host *int
	selectValues    sql.SelectValues
}

// LighthouseEdges holds the relations/edges for other nodes in the graph.
type LighthouseEdges struct {
	// Host holds the value of the host edge.
	Host *Host `json:"host,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HostOrErr returns the Host value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LighthouseEdges) HostOrErr() (*Host, error) {
	if e.Host != nil {
		return e.Host, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: host.Label}
	}
	return nil, &NotLoadedError{edge: "host"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Lighthouse) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lighthouse.FieldCertificate, lighthouse.FieldKey:
			values[i] = new(helpers.EncryptedBytes)
		case lighthouse.FieldID, lighthouse.FieldIP:
			values[i] = new(sql.NullInt64)
		case lighthouse.FieldEndpoint, lighthouse.FieldAPIEndpoint:
			values[i] = new(sql.NullString)
		case lighthouse.FieldCreatedTime, lighthouse.FieldUpdatedTime:
			values[i] = new(sql.NullTime)
		case lighthouse.ForeignKeys[0]: // lighthouse_host
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Lighthouse fields.
func (_m *Lighthouse) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lighthouse.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case lighthouse.FieldCreatedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_time", values[i])
			} else if value.Valid {
				_m.CreatedTime = value.Time
			}
		case lighthouse.FieldUpdatedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_time", values[i])
			} else if value.Valid {
				_m.UpdatedTime = value.Time
			}
		case lighthouse.FieldIP:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = ipconv.IP(value.Int64)
			}
		case lighthouse.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case lighthouse.FieldCertificate:
			if value, ok := values[i].(*helpers.EncryptedBytes); !ok {
				return fmt.Errorf("unexpected type %T for field certificate", values[i])
			} else if value != nil {
				_m.Certificate = *value
			}
		case lighthouse.FieldKey:
			if value, ok := values[i].(*helpers.EncryptedBytes); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value != nil {
				_m.Key = *value
			}
		case lighthouse.FieldAPIEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_endpoint", values[i])
			} else if value.Valid {
				_m.APIEndpoint = value.String
			}
		case lighthouse.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field lighthouse_host", value)
			} else if value.Valid {
				_m.lighthouse_host = new(int)
				*_m.lighthouse_host = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Lighthouse.
// This includes values selected through modifiers, order, etc.
func (_m *Lighthouse) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHost queries the "host" edge of the Lighthouse entity.
func (_m *Lighthouse) QueryHost() *HostQuery {
	return NewLighthouseClient(_m.config).QueryHost(_m)
}

// Update returns a builder for updating this Lighthouse.
// Note that you need to call Lighthouse.Unwrap() before calling this method if this Lighthouse
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Lighthouse) Update() *LighthouseUpdateOne {
	return NewLighthouseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Lighthouse entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Lighthouse) Unwrap() *Lighthouse {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Lighthouse is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Lighthouse) String() string {
	var builder strings.Builder
	builder.WriteString("Lighthouse(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_time=")
	builder.WriteString(_m.CreatedTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_time=")
	builder.WriteString(_m.UpdatedTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(fmt.Sprintf("%v", _m.IP))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("certificate=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("api_endpoint=")
	builder.WriteString(_m.APIEndpoint)
	builder.WriteByte(')')
	return builder.String()
}

// Lighthouses is a parsable slice of Lighthouse.
type Lighthouses []*Lighthouse
