// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sprisa/west/util/ipconv"
	"github.com/sprisa/west/westport/db/ent/device"
	"github.com/sprisa/west/westport/db/ent/predicate"
	"github.com/sprisa/west/westport/db/ent/settings"
	"github.com/sprisa/west/westport/db/helpers"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDevice   = "Device"
	TypeSettings = "Settings"
)

// DeviceMutation represents an operation that mutates the Device nodes in the graph.
type DeviceMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	created_time        *time.Time
	updated_time        *time.Time
	name                *string
	ip                  *ipconv.IP
	addip               *ipconv.IP
	leased_access_token *string
	token               *helpers.EncryptedBytes
	clearedFields       map[string]struct{}
	done                bool
	oldValue            func(context.Context) (*Device, error)
	predicates          []predicate.Device
}

var _ ent.Mutation = (*DeviceMutation)(nil)

// deviceOption allows management of the mutation configuration using functional options.
type deviceOption func(*DeviceMutation)

// newDeviceMutation creates new mutation for the Device entity.
func newDeviceMutation(c config, op Op, opts ...deviceOption) *DeviceMutation {
	m := &DeviceMutation{
		config:        c,
		op:            op,
		typ:           TypeDevice,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDeviceID sets the ID field of the mutation.
func withDeviceID(id int) deviceOption {
	return func(m *DeviceMutation) {
		var (
			err   error
			once  sync.Once
			value *Device
		)
		m.oldValue = func(ctx context.Context) (*Device, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Device.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDevice sets the old Device of the mutation.
func withDevice(node *Device) deviceOption {
	return func(m *DeviceMutation) {
		m.oldValue = func(context.Context) (*Device, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DeviceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DeviceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DeviceMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DeviceMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Device.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedTime sets the "created_time" field.
func (m *DeviceMutation) SetCreatedTime(t time.Time) {
	m.created_time = &t
}

// CreatedTime returns the value of the "created_time" field in the mutation.
func (m *DeviceMutation) CreatedTime() (r time.Time, exists bool) {
	v := m.created_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedTime returns the old "created_time" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldCreatedTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedTime: %w", err)
	}
	return oldValue.CreatedTime, nil
}

// ResetCreatedTime resets all changes to the "created_time" field.
func (m *DeviceMutation) ResetCreatedTime() {
	m.created_time = nil
}

// SetUpdatedTime sets the "updated_time" field.
func (m *DeviceMutation) SetUpdatedTime(t time.Time) {
	m.updated_time = &t
}

// UpdatedTime returns the value of the "updated_time" field in the mutation.
func (m *DeviceMutation) UpdatedTime() (r time.Time, exists bool) {
	v := m.updated_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedTime returns the old "updated_time" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldUpdatedTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedTime: %w", err)
	}
	return oldValue.UpdatedTime, nil
}

// ResetUpdatedTime resets all changes to the "updated_time" field.
func (m *DeviceMutation) ResetUpdatedTime() {
	m.updated_time = nil
}

// SetName sets the "name" field.
func (m *DeviceMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DeviceMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *DeviceMutation) ResetName() {
	m.name = nil
}

// SetIP sets the "ip" field.
func (m *DeviceMutation) SetIP(i ipconv.IP) {
	m.ip = &i
	m.addip = nil
}

// IP returns the value of the "ip" field in the mutation.
func (m *DeviceMutation) IP() (r ipconv.IP, exists bool) {
	v := m.ip
	if v == nil {
		return
	}
	return *v, true
}

// OldIP returns the old "ip" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldIP(ctx context.Context) (v ipconv.IP, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIP: %w", err)
	}
	return oldValue.IP, nil
}

// AddIP adds i to the "ip" field.
func (m *DeviceMutation) AddIP(i ipconv.IP) {
	if m.addip != nil {
		*m.addip += i
	} else {
		m.addip = &i
	}
}

// AddedIP returns the value that was added to the "ip" field in this mutation.
func (m *DeviceMutation) AddedIP() (r ipconv.IP, exists bool) {
	v := m.addip
	if v == nil {
		return
	}
	return *v, true
}

// ResetIP resets all changes to the "ip" field.
func (m *DeviceMutation) ResetIP() {
	m.ip = nil
	m.addip = nil
}

// SetLeasedAccessToken sets the "leased_access_token" field.
func (m *DeviceMutation) SetLeasedAccessToken(s string) {
	m.leased_access_token = &s
}

// LeasedAccessToken returns the value of the "leased_access_token" field in the mutation.
func (m *DeviceMutation) LeasedAccessToken() (r string, exists bool) {
	v := m.leased_access_token
	if v == nil {
		return
	}
	return *v, true
}

// OldLeasedAccessToken returns the old "leased_access_token" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldLeasedAccessToken(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLeasedAccessToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLeasedAccessToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLeasedAccessToken: %w", err)
	}
	return oldValue.LeasedAccessToken, nil
}

// ClearLeasedAccessToken clears the value of the "leased_access_token" field.
func (m *DeviceMutation) ClearLeasedAccessToken() {
	m.leased_access_token = nil
	m.clearedFields[device.FieldLeasedAccessToken] = struct{}{}
}

// LeasedAccessTokenCleared returns if the "leased_access_token" field was cleared in this mutation.
func (m *DeviceMutation) LeasedAccessTokenCleared() bool {
	_, ok := m.clearedFields[device.FieldLeasedAccessToken]
	return ok
}

// ResetLeasedAccessToken resets all changes to the "leased_access_token" field.
func (m *DeviceMutation) ResetLeasedAccessToken() {
	m.leased_access_token = nil
	delete(m.clearedFields, device.FieldLeasedAccessToken)
}

// SetToken sets the "token" field.
func (m *DeviceMutation) SetToken(hb helpers.EncryptedBytes) {
	m.token = &hb
}

// Token returns the value of the "token" field in the mutation.
func (m *DeviceMutation) Token() (r helpers.EncryptedBytes, exists bool) {
	v := m.token
	if v == nil {
		return
	}
	return *v, true
}

// OldToken returns the old "token" field's value of the Device entity.
// If the Device object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeviceMutation) OldToken(ctx context.Context) (v helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToken: %w", err)
	}
	return oldValue.Token, nil
}

// ResetToken resets all changes to the "token" field.
func (m *DeviceMutation) ResetToken() {
	m.token = nil
}

// Where appends a list predicates to the DeviceMutation builder.
func (m *DeviceMutation) Where(ps ...predicate.Device) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DeviceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DeviceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Device, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DeviceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DeviceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Device).
func (m *DeviceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DeviceMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_time != nil {
		fields = append(fields, device.FieldCreatedTime)
	}
	if m.updated_time != nil {
		fields = append(fields, device.FieldUpdatedTime)
	}
	if m.name != nil {
		fields = append(fields, device.FieldName)
	}
	if m.ip != nil {
		fields = append(fields, device.FieldIP)
	}
	if m.leased_access_token != nil {
		fields = append(fields, device.FieldLeasedAccessToken)
	}
	if m.token != nil {
		fields = append(fields, device.FieldToken)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DeviceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case device.FieldCreatedTime:
		return m.CreatedTime()
	case device.FieldUpdatedTime:
		return m.UpdatedTime()
	case device.FieldName:
		return m.Name()
	case device.FieldIP:
		return m.IP()
	case device.FieldLeasedAccessToken:
		return m.LeasedAccessToken()
	case device.FieldToken:
		return m.Token()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DeviceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case device.FieldCreatedTime:
		return m.OldCreatedTime(ctx)
	case device.FieldUpdatedTime:
		return m.OldUpdatedTime(ctx)
	case device.FieldName:
		return m.OldName(ctx)
	case device.FieldIP:
		return m.OldIP(ctx)
	case device.FieldLeasedAccessToken:
		return m.OldLeasedAccessToken(ctx)
	case device.FieldToken:
		return m.OldToken(ctx)
	}
	return nil, fmt.Errorf("unknown Device field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeviceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case device.FieldCreatedTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedTime(v)
		return nil
	case device.FieldUpdatedTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedTime(v)
		return nil
	case device.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case device.FieldIP:
		v, ok := value.(ipconv.IP)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIP(v)
		return nil
	case device.FieldLeasedAccessToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLeasedAccessToken(v)
		return nil
	case device.FieldToken:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToken(v)
		return nil
	}
	return fmt.Errorf("unknown Device field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DeviceMutation) AddedFields() []string {
	var fields []string
	if m.addip != nil {
		fields = append(fields, device.FieldIP)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DeviceMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case device.FieldIP:
		return m.AddedIP()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeviceMutation) AddField(name string, value ent.Value) error {
	switch name {
	case device.FieldIP:
		v, ok := value.(ipconv.IP)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddIP(v)
		return nil
	}
	return fmt.Errorf("unknown Device numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DeviceMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(device.FieldLeasedAccessToken) {
		fields = append(fields, device.FieldLeasedAccessToken)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DeviceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DeviceMutation) ClearField(name string) error {
	switch name {
	case device.FieldLeasedAccessToken:
		m.ClearLeasedAccessToken()
		return nil
	}
	return fmt.Errorf("unknown Device nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DeviceMutation) ResetField(name string) error {
	switch name {
	case device.FieldCreatedTime:
		m.ResetCreatedTime()
		return nil
	case device.FieldUpdatedTime:
		m.ResetUpdatedTime()
		return nil
	case device.FieldName:
		m.ResetName()
		return nil
	case device.FieldIP:
		m.ResetIP()
		return nil
	case device.FieldLeasedAccessToken:
		m.ResetLeasedAccessToken()
		return nil
	case device.FieldToken:
		m.ResetToken()
		return nil
	}
	return fmt.Errorf("unknown Device field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DeviceMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DeviceMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DeviceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DeviceMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DeviceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DeviceMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DeviceMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Device unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DeviceMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Device edge %s", name)
}

// SettingsMutation represents an operation that mutates the Settings nodes in the graph.
type SettingsMutation struct {
	config
	op                       Op
	typ                      string
	id                       *int
	created_time             *time.Time
	updated_time             *time.Time
	domain_zone              *string
	cipher                   *string
	ca_crt                   *helpers.EncryptedBytes
	ca_key                   *helpers.EncryptedBytes
	lighthouse_crt           *helpers.EncryptedBytes
	lighthouse_key           *helpers.EncryptedBytes
	cidr                     *helpers.IpCidr
	port_overlay_ip          *ipconv.IP
	addport_overlay_ip       *ipconv.IP
	letsencrypt_registration *helpers.EncryptedBytes
	tls_cert                 *helpers.EncryptedBytes
	tls_cert_key             *helpers.EncryptedBytes
	clearedFields            map[string]struct{}
	done                     bool
	oldValue                 func(context.Context) (*Settings, error)
	predicates               []predicate.Settings
}

var _ ent.Mutation = (*SettingsMutation)(nil)

// settingsOption allows management of the mutation configuration using functional options.
type settingsOption func(*SettingsMutation)

// newSettingsMutation creates new mutation for the Settings entity.
func newSettingsMutation(c config, op Op, opts ...settingsOption) *SettingsMutation {
	m := &SettingsMutation{
		config:        c,
		op:            op,
		typ:           TypeSettings,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSettingsID sets the ID field of the mutation.
func withSettingsID(id int) settingsOption {
	return func(m *SettingsMutation) {
		var (
			err   error
			once  sync.Once
			value *Settings
		)
		m.oldValue = func(ctx context.Context) (*Settings, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Settings.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSettings sets the old Settings of the mutation.
func withSettings(node *Settings) settingsOption {
	return func(m *SettingsMutation) {
		m.oldValue = func(context.Context) (*Settings, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SettingsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SettingsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SettingsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SettingsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Settings.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedTime sets the "created_time" field.
func (m *SettingsMutation) SetCreatedTime(t time.Time) {
	m.created_time = &t
}

// CreatedTime returns the value of the "created_time" field in the mutation.
func (m *SettingsMutation) CreatedTime() (r time.Time, exists bool) {
	v := m.created_time
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedTime returns the old "created_time" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldCreatedTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedTime: %w", err)
	}
	return oldValue.CreatedTime, nil
}

// ResetCreatedTime resets all changes to the "created_time" field.
func (m *SettingsMutation) ResetCreatedTime() {
	m.created_time = nil
}

// SetUpdatedTime sets the "updated_time" field.
func (m *SettingsMutation) SetUpdatedTime(t time.Time) {
	m.updated_time = &t
}

// UpdatedTime returns the value of the "updated_time" field in the mutation.
func (m *SettingsMutation) UpdatedTime() (r time.Time, exists bool) {
	v := m.updated_time
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedTime returns the old "updated_time" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldUpdatedTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedTime: %w", err)
	}
	return oldValue.UpdatedTime, nil
}

// ResetUpdatedTime resets all changes to the "updated_time" field.
func (m *SettingsMutation) ResetUpdatedTime() {
	m.updated_time = nil
}

// SetDomainZone sets the "domain_zone" field.
func (m *SettingsMutation) SetDomainZone(s string) {
	m.domain_zone = &s
}

// DomainZone returns the value of the "domain_zone" field in the mutation.
func (m *SettingsMutation) DomainZone() (r string, exists bool) {
	v := m.domain_zone
	if v == nil {
		return
	}
	return *v, true
}

// OldDomainZone returns the old "domain_zone" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldDomainZone(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDomainZone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDomainZone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDomainZone: %w", err)
	}
	return oldValue.DomainZone, nil
}

// ClearDomainZone clears the value of the "domain_zone" field.
func (m *SettingsMutation) ClearDomainZone() {
	m.domain_zone = nil
	m.clearedFields[settings.FieldDomainZone] = struct{}{}
}

// DomainZoneCleared returns if the "domain_zone" field was cleared in this mutation.
func (m *SettingsMutation) DomainZoneCleared() bool {
	_, ok := m.clearedFields[settings.FieldDomainZone]
	return ok
}

// ResetDomainZone resets all changes to the "domain_zone" field.
func (m *SettingsMutation) ResetDomainZone() {
	m.domain_zone = nil
	delete(m.clearedFields, settings.FieldDomainZone)
}

// SetCipher sets the "cipher" field.
func (m *SettingsMutation) SetCipher(s string) {
	m.cipher = &s
}

// Cipher returns the value of the "cipher" field in the mutation.
func (m *SettingsMutation) Cipher() (r string, exists bool) {
	v := m.cipher
	if v == nil {
		return
	}
	return *v, true
}

// OldCipher returns the old "cipher" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldCipher(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCipher is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCipher requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCipher: %w", err)
	}
	return oldValue.Cipher, nil
}

// ResetCipher resets all changes to the "cipher" field.
func (m *SettingsMutation) ResetCipher() {
	m.cipher = nil
}

// SetCaCrt sets the "ca_crt" field.
func (m *SettingsMutation) SetCaCrt(hb helpers.EncryptedBytes) {
	m.ca_crt = &hb
}

// CaCrt returns the value of the "ca_crt" field in the mutation.
func (m *SettingsMutation) CaCrt() (r helpers.EncryptedBytes, exists bool) {
	v := m.ca_crt
	if v == nil {
		return
	}
	return *v, true
}

// OldCaCrt returns the old "ca_crt" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldCaCrt(ctx context.Context) (v helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCaCrt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCaCrt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCaCrt: %w", err)
	}
	return oldValue.CaCrt, nil
}

// ResetCaCrt resets all changes to the "ca_crt" field.
func (m *SettingsMutation) ResetCaCrt() {
	m.ca_crt = nil
}

// SetCaKey sets the "ca_key" field.
func (m *SettingsMutation) SetCaKey(hb helpers.EncryptedBytes) {
	m.ca_key = &hb
}

// CaKey returns the value of the "ca_key" field in the mutation.
func (m *SettingsMutation) CaKey() (r helpers.EncryptedBytes, exists bool) {
	v := m.ca_key
	if v == nil {
		return
	}
	return *v, true
}

// OldCaKey returns the old "ca_key" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldCaKey(ctx context.Context) (v helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCaKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCaKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCaKey: %w", err)
	}
	return oldValue.CaKey, nil
}

// ResetCaKey resets all changes to the "ca_key" field.
func (m *SettingsMutation) ResetCaKey() {
	m.ca_key = nil
}

// SetLighthouseCrt sets the "lighthouse_crt" field.
func (m *SettingsMutation) SetLighthouseCrt(hb helpers.EncryptedBytes) {
	m.lighthouse_crt = &hb
}

// LighthouseCrt returns the value of the "lighthouse_crt" field in the mutation.
func (m *SettingsMutation) LighthouseCrt() (r helpers.EncryptedBytes, exists bool) {
	v := m.lighthouse_crt
	if v == nil {
		return
	}
	return *v, true
}

// OldLighthouseCrt returns the old "lighthouse_crt" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldLighthouseCrt(ctx context.Context) (v helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLighthouseCrt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLighthouseCrt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLighthouseCrt: %w", err)
	}
	return oldValue.LighthouseCrt, nil
}

// ResetLighthouseCrt resets all changes to the "lighthouse_crt" field.
func (m *SettingsMutation) ResetLighthouseCrt() {
	m.lighthouse_crt = nil
}

// SetLighthouseKey sets the "lighthouse_key" field.
func (m *SettingsMutation) SetLighthouseKey(hb helpers.EncryptedBytes) {
	m.lighthouse_key = &hb
}

// LighthouseKey returns the value of the "lighthouse_key" field in the mutation.
func (m *SettingsMutation) LighthouseKey() (r helpers.EncryptedBytes, exists bool) {
	v := m.lighthouse_key
	if v == nil {
		return
	}
	return *v, true
}

// OldLighthouseKey returns the old "lighthouse_key" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldLighthouseKey(ctx context.Context) (v helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLighthouseKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLighthouseKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLighthouseKey: %w", err)
	}
	return oldValue.LighthouseKey, nil
}

// ResetLighthouseKey resets all changes to the "lighthouse_key" field.
func (m *SettingsMutation) ResetLighthouseKey() {
	m.lighthouse_key = nil
}

// SetCidr sets the "cidr" field.
func (m *SettingsMutation) SetCidr(hc helpers.IpCidr) {
	m.cidr = &hc
}

// Cidr returns the value of the "cidr" field in the mutation.
func (m *SettingsMutation) Cidr() (r helpers.IpCidr, exists bool) {
	v := m.cidr
	if v == nil {
		return
	}
	return *v, true
}

// OldCidr returns the old "cidr" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldCidr(ctx context.Context) (v helpers.IpCidr, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCidr is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCidr requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCidr: %w", err)
	}
	return oldValue.Cidr, nil
}

// ResetCidr resets all changes to the "cidr" field.
func (m *SettingsMutation) ResetCidr() {
	m.cidr = nil
}

// SetPortOverlayIP sets the "port_overlay_ip" field.
func (m *SettingsMutation) SetPortOverlayIP(i ipconv.IP) {
	m.port_overlay_ip = &i
	m.addport_overlay_ip = nil
}

// PortOverlayIP returns the value of the "port_overlay_ip" field in the mutation.
func (m *SettingsMutation) PortOverlayIP() (r ipconv.IP, exists bool) {
	v := m.port_overlay_ip
	if v == nil {
		return
	}
	return *v, true
}

// OldPortOverlayIP returns the old "port_overlay_ip" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldPortOverlayIP(ctx context.Context) (v ipconv.IP, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPortOverlayIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPortOverlayIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPortOverlayIP: %w", err)
	}
	return oldValue.PortOverlayIP, nil
}

// AddPortOverlayIP adds i to the "port_overlay_ip" field.
func (m *SettingsMutation) AddPortOverlayIP(i ipconv.IP) {
	if m.addport_overlay_ip != nil {
		*m.addport_overlay_ip += i
	} else {
		m.addport_overlay_ip = &i
	}
}

// AddedPortOverlayIP returns the value that was added to the "port_overlay_ip" field in this mutation.
func (m *SettingsMutation) AddedPortOverlayIP() (r ipconv.IP, exists bool) {
	v := m.addport_overlay_ip
	if v == nil {
		return
	}
	return *v, true
}

// ResetPortOverlayIP resets all changes to the "port_overlay_ip" field.
func (m *SettingsMutation) ResetPortOverlayIP() {
	m.port_overlay_ip = nil
	m.addport_overlay_ip = nil
}

// SetLetsencryptRegistration sets the "letsencrypt_registration" field.
func (m *SettingsMutation) SetLetsencryptRegistration(hb helpers.EncryptedBytes) {
	m.letsencrypt_registration = &hb
}

// LetsencryptRegistration returns the value of the "letsencrypt_registration" field in the mutation.
func (m *SettingsMutation) LetsencryptRegistration() (r helpers.EncryptedBytes, exists bool) {
	v := m.letsencrypt_registration
	if v == nil {
		return
	}
	return *v, true
}

// OldLetsencryptRegistration returns the old "letsencrypt_registration" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldLetsencryptRegistration(ctx context.Context) (v helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLetsencryptRegistration is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLetsencryptRegistration requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLetsencryptRegistration: %w", err)
	}
	return oldValue.LetsencryptRegistration, nil
}

// ClearLetsencryptRegistration clears the value of the "letsencrypt_registration" field.
func (m *SettingsMutation) ClearLetsencryptRegistration() {
	m.letsencrypt_registration = nil
	m.clearedFields[settings.FieldLetsencryptRegistration] = struct{}{}
}

// LetsencryptRegistrationCleared returns if the "letsencrypt_registration" field was cleared in this mutation.
func (m *SettingsMutation) LetsencryptRegistrationCleared() bool {
	_, ok := m.clearedFields[settings.FieldLetsencryptRegistration]
	return ok
}

// ResetLetsencryptRegistration resets all changes to the "letsencrypt_registration" field.
func (m *SettingsMutation) ResetLetsencryptRegistration() {
	m.letsencrypt_registration = nil
	delete(m.clearedFields, settings.FieldLetsencryptRegistration)
}

// SetTLSCert sets the "tls_cert" field.
func (m *SettingsMutation) SetTLSCert(hb helpers.EncryptedBytes) {
	m.tls_cert = &hb
}

// TLSCert returns the value of the "tls_cert" field in the mutation.
func (m *SettingsMutation) TLSCert() (r helpers.EncryptedBytes, exists bool) {
	v := m.tls_cert
	if v == nil {
		return
	}
	return *v, true
}

// OldTLSCert returns the old "tls_cert" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldTLSCert(ctx context.Context) (v *helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTLSCert is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTLSCert requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTLSCert: %w", err)
	}
	return oldValue.TLSCert, nil
}

// ClearTLSCert clears the value of the "tls_cert" field.
func (m *SettingsMutation) ClearTLSCert() {
	m.tls_cert = nil
	m.clearedFields[settings.FieldTLSCert] = struct{}{}
}

// TLSCertCleared returns if the "tls_cert" field was cleared in this mutation.
func (m *SettingsMutation) TLSCertCleared() bool {
	_, ok := m.clearedFields[settings.FieldTLSCert]
	return ok
}

// ResetTLSCert resets all changes to the "tls_cert" field.
func (m *SettingsMutation) ResetTLSCert() {
	m.tls_cert = nil
	delete(m.clearedFields, settings.FieldTLSCert)
}

// SetTLSCertKey sets the "tls_cert_key" field.
func (m *SettingsMutation) SetTLSCertKey(hb helpers.EncryptedBytes) {
	m.tls_cert_key = &hb
}

// TLSCertKey returns the value of the "tls_cert_key" field in the mutation.
func (m *SettingsMutation) TLSCertKey() (r helpers.EncryptedBytes, exists bool) {
	v := m.tls_cert_key
	if v == nil {
		return
	}
	return *v, true
}

// OldTLSCertKey returns the old "tls_cert_key" field's value of the Settings entity.
// If the Settings object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingsMutation) OldTLSCertKey(ctx context.Context) (v *helpers.EncryptedBytes, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTLSCertKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTLSCertKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTLSCertKey: %w", err)
	}
	return oldValue.TLSCertKey, nil
}

// ClearTLSCertKey clears the value of the "tls_cert_key" field.
func (m *SettingsMutation) ClearTLSCertKey() {
	m.tls_cert_key = nil
	m.clearedFields[settings.FieldTLSCertKey] = struct{}{}
}

// TLSCertKeyCleared returns if the "tls_cert_key" field was cleared in this mutation.
func (m *SettingsMutation) TLSCertKeyCleared() bool {
	_, ok := m.clearedFields[settings.FieldTLSCertKey]
	return ok
}

// ResetTLSCertKey resets all changes to the "tls_cert_key" field.
func (m *SettingsMutation) ResetTLSCertKey() {
	m.tls_cert_key = nil
	delete(m.clearedFields, settings.FieldTLSCertKey)
}

// Where appends a list predicates to the SettingsMutation builder.
func (m *SettingsMutation) Where(ps ...predicate.Settings) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SettingsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SettingsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Settings, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SettingsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SettingsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Settings).
func (m *SettingsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SettingsMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.created_time != nil {
		fields = append(fields, settings.FieldCreatedTime)
	}
	if m.updated_time != nil {
		fields = append(fields, settings.FieldUpdatedTime)
	}
	if m.domain_zone != nil {
		fields = append(fields, settings.FieldDomainZone)
	}
	if m.cipher != nil {
		fields = append(fields, settings.FieldCipher)
	}
	if m.ca_crt != nil {
		fields = append(fields, settings.FieldCaCrt)
	}
	if m.ca_key != nil {
		fields = append(fields, settings.FieldCaKey)
	}
	if m.lighthouse_crt != nil {
		fields = append(fields, settings.FieldLighthouseCrt)
	}
	if m.lighthouse_key != nil {
		fields = append(fields, settings.FieldLighthouseKey)
	}
	if m.cidr != nil {
		fields = append(fields, settings.FieldCidr)
	}
	if m.port_overlay_ip != nil {
		fields = append(fields, settings.FieldPortOverlayIP)
	}
	if m.letsencrypt_registration != nil {
		fields = append(fields, settings.FieldLetsencryptRegistration)
	}
	if m.tls_cert != nil {
		fields = append(fields, settings.FieldTLSCert)
	}
	if m.tls_cert_key != nil {
		fields = append(fields, settings.FieldTLSCertKey)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SettingsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case settings.FieldCreatedTime:
		return m.CreatedTime()
	case settings.FieldUpdatedTime:
		return m.UpdatedTime()
	case settings.FieldDomainZone:
		return m.DomainZone()
	case settings.FieldCipher:
		return m.Cipher()
	case settings.FieldCaCrt:
		return m.CaCrt()
	case settings.FieldCaKey:
		return m.CaKey()
	case settings.FieldLighthouseCrt:
		return m.LighthouseCrt()
	case settings.FieldLighthouseKey:
		return m.LighthouseKey()
	case settings.FieldCidr:
		return m.Cidr()
	case settings.FieldPortOverlayIP:
		return m.PortOverlayIP()
	case settings.FieldLetsencryptRegistration:
		return m.LetsencryptRegistration()
	case settings.FieldTLSCert:
		return m.TLSCert()
	case settings.FieldTLSCertKey:
		return m.TLSCertKey()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SettingsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case settings.FieldCreatedTime:
		return m.OldCreatedTime(ctx)
	case settings.FieldUpdatedTime:
		return m.OldUpdatedTime(ctx)
	case settings.FieldDomainZone:
		return m.OldDomainZone(ctx)
	case settings.FieldCipher:
		return m.OldCipher(ctx)
	case settings.FieldCaCrt:
		return m.OldCaCrt(ctx)
	case settings.FieldCaKey:
		return m.OldCaKey(ctx)
	case settings.FieldLighthouseCrt:
		return m.OldLighthouseCrt(ctx)
	case settings.FieldLighthouseKey:
		return m.OldLighthouseKey(ctx)
	case settings.FieldCidr:
		return m.OldCidr(ctx)
	case settings.FieldPortOverlayIP:
		return m.OldPortOverlayIP(ctx)
	case settings.FieldLetsencryptRegistration:
		return m.OldLetsencryptRegistration(ctx)
	case settings.FieldTLSCert:
		return m.OldTLSCert(ctx)
	case settings.FieldTLSCertKey:
		return m.OldTLSCertKey(ctx)
	}
	return nil, fmt.Errorf("unknown Settings field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case settings.FieldCreatedTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedTime(v)
		return nil
	case settings.FieldUpdatedTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedTime(v)
		return nil
	case settings.FieldDomainZone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDomainZone(v)
		return nil
	case settings.FieldCipher:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCipher(v)
		return nil
	case settings.FieldCaCrt:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCaCrt(v)
		return nil
	case settings.FieldCaKey:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCaKey(v)
		return nil
	case settings.FieldLighthouseCrt:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLighthouseCrt(v)
		return nil
	case settings.FieldLighthouseKey:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLighthouseKey(v)
		return nil
	case settings.FieldCidr:
		v, ok := value.(helpers.IpCidr)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCidr(v)
		return nil
	case settings.FieldPortOverlayIP:
		v, ok := value.(ipconv.IP)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPortOverlayIP(v)
		return nil
	case settings.FieldLetsencryptRegistration:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLetsencryptRegistration(v)
		return nil
	case settings.FieldTLSCert:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTLSCert(v)
		return nil
	case settings.FieldTLSCertKey:
		v, ok := value.(helpers.EncryptedBytes)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTLSCertKey(v)
		return nil
	}
	return fmt.Errorf("unknown Settings field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SettingsMutation) AddedFields() []string {
	var fields []string
	if m.addport_overlay_ip != nil {
		fields = append(fields, settings.FieldPortOverlayIP)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SettingsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case settings.FieldPortOverlayIP:
		return m.AddedPortOverlayIP()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case settings.FieldPortOverlayIP:
		v, ok := value.(ipconv.IP)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPortOverlayIP(v)
		return nil
	}
	return fmt.Errorf("unknown Settings numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SettingsMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(settings.FieldDomainZone) {
		fields = append(fields, settings.FieldDomainZone)
	}
	if m.FieldCleared(settings.FieldLetsencryptRegistration) {
		fields = append(fields, settings.FieldLetsencryptRegistration)
	}
	if m.FieldCleared(settings.FieldTLSCert) {
		fields = append(fields, settings.FieldTLSCert)
	}
	if m.FieldCleared(settings.FieldTLSCertKey) {
		fields = append(fields, settings.FieldTLSCertKey)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SettingsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SettingsMutation) ClearField(name string) error {
	switch name {
	case settings.FieldDomainZone:
		m.ClearDomainZone()
		return nil
	case settings.FieldLetsencryptRegistration:
		m.ClearLetsencryptRegistration()
		return nil
	case settings.FieldTLSCert:
		m.ClearTLSCert()
		return nil
	case settings.FieldTLSCertKey:
		m.ClearTLSCertKey()
		return nil
	}
	return fmt.Errorf("unknown Settings nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SettingsMutation) ResetField(name string) error {
	switch name {
	case settings.FieldCreatedTime:
		m.ResetCreatedTime()
		return nil
	case settings.FieldUpdatedTime:
		m.ResetUpdatedTime()
		return nil
	case settings.FieldDomainZone:
		m.ResetDomainZone()
		return nil
	case settings.FieldCipher:
		m.ResetCipher()
		return nil
	case settings.FieldCaCrt:
		m.ResetCaCrt()
		return nil
	case settings.FieldCaKey:
		m.ResetCaKey()
		return nil
	case settings.FieldLighthouseCrt:
		m.ResetLighthouseCrt()
		return nil
	case settings.FieldLighthouseKey:
		m.ResetLighthouseKey()
		return nil
	case settings.FieldCidr:
		m.ResetCidr()
		return nil
	case settings.FieldPortOverlayIP:
		m.ResetPortOverlayIP()
		return nil
	case settings.FieldLetsencryptRegistration:
		m.ResetLetsencryptRegistration()
		return nil
	case settings.FieldTLSCert:
		m.ResetTLSCert()
		return nil
	case settings.FieldTLSCertKey:
		m.ResetTLSCertKey()
		return nil
	}
	return fmt.Errorf("unknown Settings field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SettingsMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SettingsMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SettingsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SettingsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SettingsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SettingsMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SettingsMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Settings unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SettingsMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Settings edge %s", name)
}
