// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sprisa/west/westport/db/ent/device"
	"github.com/sprisa/west/westport/db/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceMixin := schema.Device{}.Mixin()
	deviceMixinFields0 := deviceMixin[0].Fields()
	_ = deviceMixinFields0
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescCreatedTime is the schema descriptor for created_time field.
	deviceDescCreatedTime := deviceMixinFields0[0].Descriptor()
	// device.DefaultCreatedTime holds the default value on creation for the created_time field.
	device.DefaultCreatedTime = deviceDescCreatedTime.Default.(func() time.Time)
	// deviceDescUpdatedTime is the schema descriptor for updated_time field.
	deviceDescUpdatedTime := deviceMixinFields0[1].Descriptor()
	// device.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	device.DefaultUpdatedTime = deviceDescUpdatedTime.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	device.UpdateDefaultUpdatedTime = deviceDescUpdatedTime.UpdateDefault.(func() time.Time)
	// deviceDescName is the schema descriptor for name field.
	deviceDescName := deviceFields[0].Descriptor()
	// device.DefaultName holds the default value on creation for the name field.
	device.DefaultName = deviceDescName.Default.(func() string)
	// deviceDescIP is the schema descriptor for ip field.
	deviceDescIP := deviceFields[1].Descriptor()
	// device.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	device.IPValidator = deviceDescIP.Validators[0].(func(uint32) error)
}
