// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sprisa/west/util/ipconv"
	"github.com/sprisa/west/westport/db/ent/settings"
	"github.com/sprisa/west/westport/db/helpers"
)

// SettingsCreate is the builder for creating a Settings entity.
type SettingsCreate struct {
	config
	mutation *SettingsMutation
	hooks    []Hook
}

// SetCreatedTime sets the "created_time" field.
func (_c *SettingsCreate) SetCreatedTime(v time.Time) *SettingsCreate {
	_c.mutation.SetCreatedTime(v)
	return _c
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableCreatedTime(v *time.Time) *SettingsCreate {
	if v != nil {
		_c.SetCreatedTime(*v)
	}
	return _c
}

// SetUpdatedTime sets the "updated_time" field.
func (_c *SettingsCreate) SetUpdatedTime(v time.Time) *SettingsCreate {
	_c.mutation.SetUpdatedTime(v)
	return _c
}

// SetNillableUpdatedTime sets the "updated_time" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableUpdatedTime(v *time.Time) *SettingsCreate {
	if v != nil {
		_c.SetUpdatedTime(*v)
	}
	return _c
}

// SetDomainZone sets the "domain_zone" field.
func (_c *SettingsCreate) SetDomainZone(v string) *SettingsCreate {
	_c.mutation.SetDomainZone(v)
	return _c
}

// SetNillableDomainZone sets the "domain_zone" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableDomainZone(v *string) *SettingsCreate {
	if v != nil {
		_c.SetDomainZone(*v)
	}
	return _c
}

// SetCipher sets the "cipher" field.
func (_c *SettingsCreate) SetCipher(v string) *SettingsCreate {
	_c.mutation.SetCipher(v)
	return _c
}

// SetNillableCipher sets the "cipher" field if the given value is not nil.
func (_c *SettingsCreate) SetNillableCipher(v *string) *SettingsCreate {
	if v != nil {
		_c.SetCipher(*v)
	}
	return _c
}

// SetCaCrt sets the "ca_crt" field.
func (_c *SettingsCreate) SetCaCrt(v helpers.EncryptedBytes) *SettingsCreate {
	_c.mutation.SetCaCrt(v)
	return _c
}

// SetCaKey sets the "ca_key" field.
func (_c *SettingsCreate) SetCaKey(v helpers.EncryptedBytes) *SettingsCreate {
	_c.mutation.SetCaKey(v)
	return _c
}

// SetLighthouseCrt sets the "lighthouse_crt" field.
func (_c *SettingsCreate) SetLighthouseCrt(v helpers.EncryptedBytes) *SettingsCreate {
	_c.mutation.SetLighthouseCrt(v)
	return _c
}

// SetLighthouseKey sets the "lighthouse_key" field.
func (_c *SettingsCreate) SetLighthouseKey(v helpers.EncryptedBytes) *SettingsCreate {
	_c.mutation.SetLighthouseKey(v)
	return _c
}

// SetCidr sets the "cidr" field.
func (_c *SettingsCreate) SetCidr(v helpers.IpCidr) *SettingsCreate {
	_c.mutation.SetCidr(v)
	return _c
}

// SetPortOverlayIP sets the "port_overlay_ip" field.
func (_c *SettingsCreate) SetPortOverlayIP(v ipconv.IP) *SettingsCreate {
	_c.mutation.SetPortOverlayIP(v)
	return _c
}

// SetLetsencryptRegistration sets the "letsencrypt_registration" field.
func (_c *SettingsCreate) SetLetsencryptRegistration(v helpers.EncryptedBytes) *SettingsCreate {
	_c.mutation.SetLetsencryptRegistration(v)
	return _c
}

// Mutation returns the SettingsMutation object of the builder.
func (_c *SettingsCreate) Mutation() *SettingsMutation {
	return _c.mutation
}

// Save creates the Settings in the database.
func (_c *SettingsCreate) Save(ctx context.Context) (*Settings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettingsCreate) SaveX(ctx context.Context) *Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettingsCreate) defaults() {
	if _, ok := _c.mutation.CreatedTime(); !ok {
		v := settings.DefaultCreatedTime()
		_c.mutation.SetCreatedTime(v)
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		v := settings.DefaultUpdatedTime()
		_c.mutation.SetUpdatedTime(v)
	}
	if _, ok := _c.mutation.Cipher(); !ok {
		v := settings.DefaultCipher
		_c.mutation.SetCipher(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettingsCreate) check() error {
	if _, ok := _c.mutation.CreatedTime(); !ok {
		return &ValidationError{Name: "created_time", err: errors.New(`ent: missing required field "Settings.created_time"`)}
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		return &ValidationError{Name: "updated_time", err: errors.New(`ent: missing required field "Settings.updated_time"`)}
	}
	if _, ok := _c.mutation.Cipher(); !ok {
		return &ValidationError{Name: "cipher", err: errors.New(`ent: missing required field "Settings.cipher"`)}
	}
	if _, ok := _c.mutation.CaCrt(); !ok {
		return &ValidationError{Name: "ca_crt", err: errors.New(`ent: missing required field "Settings.ca_crt"`)}
	}
	if _, ok := _c.mutation.CaKey(); !ok {
		return &ValidationError{Name: "ca_key", err: errors.New(`ent: missing required field "Settings.ca_key"`)}
	}
	if _, ok := _c.mutation.LighthouseCrt(); !ok {
		return &ValidationError{Name: "lighthouse_crt", err: errors.New(`ent: missing required field "Settings.lighthouse_crt"`)}
	}
	if _, ok := _c.mutation.LighthouseKey(); !ok {
		return &ValidationError{Name: "lighthouse_key", err: errors.New(`ent: missing required field "Settings.lighthouse_key"`)}
	}
	if _, ok := _c.mutation.Cidr(); !ok {
		return &ValidationError{Name: "cidr", err: errors.New(`ent: missing required field "Settings.cidr"`)}
	}
	if _, ok := _c.mutation.PortOverlayIP(); !ok {
		return &ValidationError{Name: "port_overlay_ip", err: errors.New(`ent: missing required field "Settings.port_overlay_ip"`)}
	}
	return nil
}

func (_c *SettingsCreate) sqlSave(ctx context.Context) (*Settings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettingsCreate) createSpec() (*Settings, *sqlgraph.CreateSpec) {
	var (
		_node = &Settings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(settings.Table, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedTime(); ok {
		_spec.SetField(settings.FieldCreatedTime, field.TypeTime, value)
		_node.CreatedTime = value
	}
	if value, ok := _c.mutation.UpdatedTime(); ok {
		_spec.SetField(settings.FieldUpdatedTime, field.TypeTime, value)
		_node.UpdatedTime = value
	}
	if value, ok := _c.mutation.DomainZone(); ok {
		_spec.SetField(settings.FieldDomainZone, field.TypeString, value)
		_node.DomainZone = value
	}
	if value, ok := _c.mutation.Cipher(); ok {
		_spec.SetField(settings.FieldCipher, field.TypeString, value)
		_node.Cipher = value
	}
	if value, ok := _c.mutation.CaCrt(); ok {
		_spec.SetField(settings.FieldCaCrt, field.TypeBytes, value)
		_node.CaCrt = value
	}
	if value, ok := _c.mutation.CaKey(); ok {
		_spec.SetField(settings.FieldCaKey, field.TypeBytes, value)
		_node.CaKey = value
	}
	if value, ok := _c.mutation.LighthouseCrt(); ok {
		_spec.SetField(settings.FieldLighthouseCrt, field.TypeBytes, value)
		_node.LighthouseCrt = value
	}
	if value, ok := _c.mutation.LighthouseKey(); ok {
		_spec.SetField(settings.FieldLighthouseKey, field.TypeBytes, value)
		_node.LighthouseKey = value
	}
	if value, ok := _c.mutation.Cidr(); ok {
		_spec.SetField(settings.FieldCidr, field.TypeString, value)
		_node.Cidr = value
	}
	if value, ok := _c.mutation.PortOverlayIP(); ok {
		_spec.SetField(settings.FieldPortOverlayIP, field.TypeUint32, value)
		_node.PortOverlayIP = value
	}
	if value, ok := _c.mutation.LetsencryptRegistration(); ok {
		_spec.SetField(settings.FieldLetsencryptRegistration, field.TypeBytes, value)
		_node.LetsencryptRegistration = value
	}
	return _node, _spec
}

// SettingsCreateBulk is the builder for creating many Settings entities in bulk.
type SettingsCreateBulk struct {
	config
	err      error
	builders []*SettingsCreate
}

// Save creates the Settings entities in the database.
func (_c *SettingsCreateBulk) Save(ctx context.Context) ([]*Settings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Settings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettingsCreateBulk) SaveX(ctx context.Context) []*Settings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
