// Code generated by ent, DO NOT EDIT.

package settings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sprisa/west/westport/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldID, id))
}

// CreatedTime applies equality check predicate on the "created_time" field. It's identical to CreatedTimeEQ.
func CreatedTime(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedTime, v))
}

// UpdatedTime applies equality check predicate on the "updated_time" field. It's identical to UpdatedTimeEQ.
func UpdatedTime(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedTime, v))
}

// Cipher applies equality check predicate on the "cipher" field. It's identical to CipherEQ.
func Cipher(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCipher, v))
}

// Hmac applies equality check predicate on the "hmac" field. It's identical to HmacEQ.
func Hmac(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHmac, v))
}

// CreatedTimeEQ applies the EQ predicate on the "created_time" field.
func CreatedTimeEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCreatedTime, v))
}

// CreatedTimeNEQ applies the NEQ predicate on the "created_time" field.
func CreatedTimeNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCreatedTime, v))
}

// CreatedTimeIn applies the In predicate on the "created_time" field.
func CreatedTimeIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCreatedTime, vs...))
}

// CreatedTimeNotIn applies the NotIn predicate on the "created_time" field.
func CreatedTimeNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCreatedTime, vs...))
}

// CreatedTimeGT applies the GT predicate on the "created_time" field.
func CreatedTimeGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCreatedTime, v))
}

// CreatedTimeGTE applies the GTE predicate on the "created_time" field.
func CreatedTimeGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCreatedTime, v))
}

// CreatedTimeLT applies the LT predicate on the "created_time" field.
func CreatedTimeLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCreatedTime, v))
}

// CreatedTimeLTE applies the LTE predicate on the "created_time" field.
func CreatedTimeLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCreatedTime, v))
}

// UpdatedTimeEQ applies the EQ predicate on the "updated_time" field.
func UpdatedTimeEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldUpdatedTime, v))
}

// UpdatedTimeNEQ applies the NEQ predicate on the "updated_time" field.
func UpdatedTimeNEQ(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldUpdatedTime, v))
}

// UpdatedTimeIn applies the In predicate on the "updated_time" field.
func UpdatedTimeIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldUpdatedTime, vs...))
}

// UpdatedTimeNotIn applies the NotIn predicate on the "updated_time" field.
func UpdatedTimeNotIn(vs ...time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldUpdatedTime, vs...))
}

// UpdatedTimeGT applies the GT predicate on the "updated_time" field.
func UpdatedTimeGT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldUpdatedTime, v))
}

// UpdatedTimeGTE applies the GTE predicate on the "updated_time" field.
func UpdatedTimeGTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldUpdatedTime, v))
}

// UpdatedTimeLT applies the LT predicate on the "updated_time" field.
func UpdatedTimeLT(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldUpdatedTime, v))
}

// UpdatedTimeLTE applies the LTE predicate on the "updated_time" field.
func UpdatedTimeLTE(v time.Time) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldUpdatedTime, v))
}

// CipherEQ applies the EQ predicate on the "cipher" field.
func CipherEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldCipher, v))
}

// CipherNEQ applies the NEQ predicate on the "cipher" field.
func CipherNEQ(v string) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldCipher, v))
}

// CipherIn applies the In predicate on the "cipher" field.
func CipherIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldCipher, vs...))
}

// CipherNotIn applies the NotIn predicate on the "cipher" field.
func CipherNotIn(vs ...string) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldCipher, vs...))
}

// CipherGT applies the GT predicate on the "cipher" field.
func CipherGT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldCipher, v))
}

// CipherGTE applies the GTE predicate on the "cipher" field.
func CipherGTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldCipher, v))
}

// CipherLT applies the LT predicate on the "cipher" field.
func CipherLT(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldCipher, v))
}

// CipherLTE applies the LTE predicate on the "cipher" field.
func CipherLTE(v string) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldCipher, v))
}

// CipherContains applies the Contains predicate on the "cipher" field.
func CipherContains(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContains(FieldCipher, v))
}

// CipherHasPrefix applies the HasPrefix predicate on the "cipher" field.
func CipherHasPrefix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasPrefix(FieldCipher, v))
}

// CipherHasSuffix applies the HasSuffix predicate on the "cipher" field.
func CipherHasSuffix(v string) predicate.Settings {
	return predicate.Settings(sql.FieldHasSuffix(FieldCipher, v))
}

// CipherEqualFold applies the EqualFold predicate on the "cipher" field.
func CipherEqualFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldEqualFold(FieldCipher, v))
}

// CipherContainsFold applies the ContainsFold predicate on the "cipher" field.
func CipherContainsFold(v string) predicate.Settings {
	return predicate.Settings(sql.FieldContainsFold(FieldCipher, v))
}

// HmacEQ applies the EQ predicate on the "hmac" field.
func HmacEQ(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldEQ(FieldHmac, v))
}

// HmacNEQ applies the NEQ predicate on the "hmac" field.
func HmacNEQ(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldNEQ(FieldHmac, v))
}

// HmacIn applies the In predicate on the "hmac" field.
func HmacIn(vs ...[]byte) predicate.Settings {
	return predicate.Settings(sql.FieldIn(FieldHmac, vs...))
}

// HmacNotIn applies the NotIn predicate on the "hmac" field.
func HmacNotIn(vs ...[]byte) predicate.Settings {
	return predicate.Settings(sql.FieldNotIn(FieldHmac, vs...))
}

// HmacGT applies the GT predicate on the "hmac" field.
func HmacGT(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldGT(FieldHmac, v))
}

// HmacGTE applies the GTE predicate on the "hmac" field.
func HmacGTE(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldGTE(FieldHmac, v))
}

// HmacLT applies the LT predicate on the "hmac" field.
func HmacLT(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldLT(FieldHmac, v))
}

// HmacLTE applies the LTE predicate on the "hmac" field.
func HmacLTE(v []byte) predicate.Settings {
	return predicate.Settings(sql.FieldLTE(FieldHmac, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Settings) predicate.Settings {
	return predicate.Settings(sql.NotPredicates(p))
}
