// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package db

type ProvisionDeviceInput struct {
	Token string `json:"token"`
}

type ProvisionDeviceResponse struct {
	Cert          string `json:"cert"`
	Key           string `json:"key"`
	AccessToken   string `json:"access_token"`
	NetworkCipher string `json:"networkCipher"`
}
