package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"net/netip"
	"time"

	jwt "github.com/golang-jwt/jwt/v5"
	"github.com/samber/lo"
	"github.com/sprisa/west/util/auth"
	"github.com/sprisa/west/util/pki"
	"github.com/sprisa/west/westport/db/ent"
	"github.com/sprisa/west/westport/db/helpers"
	"github.com/sprisa/x/errutil"
	l "github.com/sprisa/x/log"
)

// ProvisionDevice is the resolver for the provision_device field.
func (r *mutationResolver) ProvisionDevice(ctx context.Context, input ProvisionDeviceInput) (*ProvisionDeviceResponse, error) {
	settings, err := r.client.Settings.Query().Only(ctx)
	if err != nil {
		return nil, errutil.WrapErr(err, "error fetching settings")
	}
	dvcs, err := r.client.Device.Query().
		All(ctx)
	if err != nil {
		return nil, errutil.WrapErr(err, "error finding device")
	}
	// for _, dvc := range dvcs {
	// 	l.Log.Info().Msgf("%+v", dvc)
	// 	l.Log.Info().Msgf("%s", dvc.Token)
	// }

	dvc, found := lo.Find(dvcs, func(dvc *ent.Device) bool {
		return dvc.Token.String() == input.Token
	})
	if !found {
		return nil, errors.New("device not found")
	}

	// TODO: Not sure how to do a correct Where search on the encrypted token value
	// encToken, err :=  helpers.EncryptedBytes(input.Token).Value()
	// if err != nil {
	// 	return nil, errors.New("token error")
	// }

	// dvc, err := r.client.Debug().Device.Query().
	// 	Where(device.Token(helpers.EncryptedBytes(encToken.([]byte)))).
	// 	Only(ctx)
	// if err != nil {
	// 	return nil, errutil.WrapErr(err, "error finding device")
	// }

	claims := &auth.TokenClaims{}
	parser := jwt.NewParser()
	_, err = parser.ParseWithClaims(input.Token, claims, func(t *jwt.Token) (any, error) {
		return helpers.EncryptionKey[:], nil
	})
	if err != nil {
		l.Log.Err(err).Msg("ProvisionDevice: error parsing jwt")
		return nil, errors.New("error parsing jwt")
	}

	if claims.ExpiresAt.Before(time.Now()) {
		return nil, errors.New("invalid token")
	}

	ip := dvc.IP.ToIpAddr()
	nebulaIp := netip.PrefixFrom(ip, settings.Cidr.Bits())

	cert, err := pki.SignCert(&pki.SignCertOptions{
		CaCrt: settings.CaCrt,
		CaKey: settings.CaKey,
		Name:  dvc.Name,
		Ip:    nebulaIp.String(),
	})
	if err != nil {
		return nil, errutil.WrapErr(err, "error signing cert")
	}

	res := &ProvisionDeviceResponse{
		Name:          dvc.Name,
		Ca:            string(settings.CaCrt),
		Cert:          string(cert.Cert),
		Key:           string(cert.Key),
		AccessToken:   "todo",
		NetworkCipher: settings.Cipher,
	}
	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
