// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type ProvisionDeviceInput struct {
	Token string `json:"token"`
}

// GetToken returns ProvisionDeviceInput.Token, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceInput) GetToken() string { return v.Token }

// ProvisionDeviceProvision_deviceProvisionDeviceResponse includes the requested fields of the GraphQL type ProvisionDeviceResponse.
type ProvisionDeviceProvision_deviceProvisionDeviceResponse struct {
	Name          string `json:"name"`
	Ca            string `json:"ca"`
	Cert          string `json:"cert"`
	Key           string `json:"key"`
	NetworkCipher string `json:"networkCipher"`
}

// GetName returns ProvisionDeviceProvision_deviceProvisionDeviceResponse.Name, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceProvision_deviceProvisionDeviceResponse) GetName() string { return v.Name }

// GetCa returns ProvisionDeviceProvision_deviceProvisionDeviceResponse.Ca, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceProvision_deviceProvisionDeviceResponse) GetCa() string { return v.Ca }

// GetCert returns ProvisionDeviceProvision_deviceProvisionDeviceResponse.Cert, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceProvision_deviceProvisionDeviceResponse) GetCert() string { return v.Cert }

// GetKey returns ProvisionDeviceProvision_deviceProvisionDeviceResponse.Key, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceProvision_deviceProvisionDeviceResponse) GetKey() string { return v.Key }

// GetNetworkCipher returns ProvisionDeviceProvision_deviceProvisionDeviceResponse.NetworkCipher, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceProvision_deviceProvisionDeviceResponse) GetNetworkCipher() string {
	return v.NetworkCipher
}

// ProvisionDeviceResponse is returned by ProvisionDevice on success.
type ProvisionDeviceResponse struct {
	Provision_device ProvisionDeviceProvision_deviceProvisionDeviceResponse `json:"provision_device"`
}

// GetProvision_device returns ProvisionDeviceResponse.Provision_device, and is useful for accessing the field via an interface.
func (v *ProvisionDeviceResponse) GetProvision_device() ProvisionDeviceProvision_deviceProvisionDeviceResponse {
	return v.Provision_device
}

// __ProvisionDeviceInput is used internally by genqlient
type __ProvisionDeviceInput struct {
	Input ProvisionDeviceInput `json:"input"`
}

// GetInput returns __ProvisionDeviceInput.Input, and is useful for accessing the field via an interface.
func (v *__ProvisionDeviceInput) GetInput() ProvisionDeviceInput { return v.Input }

// The mutation executed by ProvisionDevice.
const ProvisionDevice_Operation = `
mutation ProvisionDevice ($input: ProvisionDeviceInput!) {
	provision_device(input: $input) {
		name
		ca
		cert
		key
		networkCipher
	}
}
`

func ProvisionDevice(
	ctx_ context.Context,
	client_ graphql.Client,
	input ProvisionDeviceInput,
) (data_ *ProvisionDeviceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ProvisionDevice",
		Query:  ProvisionDevice_Operation,
		Variables: &__ProvisionDeviceInput{
			Input: input,
		},
	}

	data_ = &ProvisionDeviceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
