// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_time", Type: field.TypeTime},
		{Name: "updated_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "ip", Type: field.TypeUint32},
		{Name: "leased_access_token", Type: field.TypeString, Nullable: true},
		{Name: "token", Type: field.TypeBytes},
		{Name: "device_host", Type: field.TypeInt},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "devices_hosts_host",
				Columns:    []*schema.Column{DevicesColumns[7]},
				RefColumns: []*schema.Column{HostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "device_ip",
				Unique:  true,
				Columns: []*schema.Column{DevicesColumns[4]},
			},
			{
				Name:    "device_name",
				Unique:  true,
				Columns: []*schema.Column{DevicesColumns[3]},
			},
		},
	}
	// HostsColumns holds the columns for the "hosts" table.
	HostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_time", Type: field.TypeTime},
		{Name: "updated_time", Type: field.TypeTime},
		{Name: "ip", Type: field.TypeUint32},
	}
	// HostsTable holds the schema information for the "hosts" table.
	HostsTable = &schema.Table{
		Name:       "hosts",
		Columns:    HostsColumns,
		PrimaryKey: []*schema.Column{HostsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "host_ip",
				Unique:  true,
				Columns: []*schema.Column{HostsColumns[3]},
			},
		},
	}
	// LighthousesColumns holds the columns for the "lighthouses" table.
	LighthousesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_time", Type: field.TypeTime},
		{Name: "updated_time", Type: field.TypeTime},
		{Name: "ip", Type: field.TypeUint32},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "certificate", Type: field.TypeBytes},
		{Name: "key", Type: field.TypeBytes},
		{Name: "api_endpoint", Type: field.TypeString},
		{Name: "lighthouse_host", Type: field.TypeInt},
	}
	// LighthousesTable holds the schema information for the "lighthouses" table.
	LighthousesTable = &schema.Table{
		Name:       "lighthouses",
		Columns:    LighthousesColumns,
		PrimaryKey: []*schema.Column{LighthousesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lighthouses_hosts_host",
				Columns:    []*schema.Column{LighthousesColumns[8]},
				RefColumns: []*schema.Column{HostsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "lighthouse_ip",
				Unique:  true,
				Columns: []*schema.Column{LighthousesColumns[3]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_time", Type: field.TypeTime},
		{Name: "updated_time", Type: field.TypeTime},
		{Name: "network_id", Type: field.TypeString, Default: "default"},
		{Name: "domain_zone", Type: field.TypeString, Nullable: true},
		{Name: "cipher", Type: field.TypeString, Default: "aes"},
		{Name: "ca_crt", Type: field.TypeBytes},
		{Name: "ca_key", Type: field.TypeBytes},
		{Name: "cidr", Type: field.TypeString},
		{Name: "letsencrypt_registration", Type: field.TypeBytes, Nullable: true},
		{Name: "tls_cert", Type: field.TypeBytes, Nullable: true},
		{Name: "tls_cert_key", Type: field.TypeBytes, Nullable: true},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "settings_network_id",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
		HostsTable,
		LighthousesTable,
		SettingsTable,
	}
)

func init() {
	DevicesTable.ForeignKeys[0].RefTable = HostsTable
	LighthousesTable.ForeignKeys[0].RefTable = HostsTable
}
