// Code generated by ent, DO NOT EDIT.

package lighthouse

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/sprisa/west/util/ipconv"
	"github.com/sprisa/west/westport/db/ent/predicate"
	"github.com/sprisa/west/westport/db/helpers"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldID, id))
}

// CreatedTime applies equality check predicate on the "created_time" field. It's identical to CreatedTimeEQ.
func CreatedTime(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldCreatedTime, v))
}

// UpdatedTime applies equality check predicate on the "updated_time" field. It's identical to UpdatedTimeEQ.
func UpdatedTime(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldUpdatedTime, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldEQ(FieldIP, vc))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldEndpoint, v))
}

// Certificate applies equality check predicate on the "certificate" field. It's identical to CertificateEQ.
func Certificate(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldCertificate, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldKey, v))
}

// APIEndpoint applies equality check predicate on the "api_endpoint" field. It's identical to APIEndpointEQ.
func APIEndpoint(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldAPIEndpoint, v))
}

// CreatedTimeEQ applies the EQ predicate on the "created_time" field.
func CreatedTimeEQ(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldCreatedTime, v))
}

// CreatedTimeNEQ applies the NEQ predicate on the "created_time" field.
func CreatedTimeNEQ(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldCreatedTime, v))
}

// CreatedTimeIn applies the In predicate on the "created_time" field.
func CreatedTimeIn(vs ...time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldCreatedTime, vs...))
}

// CreatedTimeNotIn applies the NotIn predicate on the "created_time" field.
func CreatedTimeNotIn(vs ...time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldCreatedTime, vs...))
}

// CreatedTimeGT applies the GT predicate on the "created_time" field.
func CreatedTimeGT(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldCreatedTime, v))
}

// CreatedTimeGTE applies the GTE predicate on the "created_time" field.
func CreatedTimeGTE(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldCreatedTime, v))
}

// CreatedTimeLT applies the LT predicate on the "created_time" field.
func CreatedTimeLT(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldCreatedTime, v))
}

// CreatedTimeLTE applies the LTE predicate on the "created_time" field.
func CreatedTimeLTE(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldCreatedTime, v))
}

// UpdatedTimeEQ applies the EQ predicate on the "updated_time" field.
func UpdatedTimeEQ(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldUpdatedTime, v))
}

// UpdatedTimeNEQ applies the NEQ predicate on the "updated_time" field.
func UpdatedTimeNEQ(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldUpdatedTime, v))
}

// UpdatedTimeIn applies the In predicate on the "updated_time" field.
func UpdatedTimeIn(vs ...time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldUpdatedTime, vs...))
}

// UpdatedTimeNotIn applies the NotIn predicate on the "updated_time" field.
func UpdatedTimeNotIn(vs ...time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldUpdatedTime, vs...))
}

// UpdatedTimeGT applies the GT predicate on the "updated_time" field.
func UpdatedTimeGT(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldUpdatedTime, v))
}

// UpdatedTimeGTE applies the GTE predicate on the "updated_time" field.
func UpdatedTimeGTE(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldUpdatedTime, v))
}

// UpdatedTimeLT applies the LT predicate on the "updated_time" field.
func UpdatedTimeLT(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldUpdatedTime, v))
}

// UpdatedTimeLTE applies the LTE predicate on the "updated_time" field.
func UpdatedTimeLTE(v time.Time) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldUpdatedTime, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldEQ(FieldIP, vc))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldNEQ(FieldIP, vc))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...ipconv.IP) predicate.Lighthouse {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = uint32(vs[i])
	}
	return predicate.Lighthouse(sql.FieldIn(FieldIP, v...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...ipconv.IP) predicate.Lighthouse {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = uint32(vs[i])
	}
	return predicate.Lighthouse(sql.FieldNotIn(FieldIP, v...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldGT(FieldIP, vc))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldGTE(FieldIP, vc))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldLT(FieldIP, vc))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v ipconv.IP) predicate.Lighthouse {
	vc := uint32(v)
	return predicate.Lighthouse(sql.FieldLTE(FieldIP, vc))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldContainsFold(FieldEndpoint, v))
}

// CertificateEQ applies the EQ predicate on the "certificate" field.
func CertificateEQ(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldCertificate, v))
}

// CertificateNEQ applies the NEQ predicate on the "certificate" field.
func CertificateNEQ(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldCertificate, v))
}

// CertificateIn applies the In predicate on the "certificate" field.
func CertificateIn(vs ...helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldCertificate, vs...))
}

// CertificateNotIn applies the NotIn predicate on the "certificate" field.
func CertificateNotIn(vs ...helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldCertificate, vs...))
}

// CertificateGT applies the GT predicate on the "certificate" field.
func CertificateGT(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldCertificate, v))
}

// CertificateGTE applies the GTE predicate on the "certificate" field.
func CertificateGTE(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldCertificate, v))
}

// CertificateLT applies the LT predicate on the "certificate" field.
func CertificateLT(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldCertificate, v))
}

// CertificateLTE applies the LTE predicate on the "certificate" field.
func CertificateLTE(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldCertificate, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v helpers.EncryptedBytes) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldKey, v))
}

// APIEndpointEQ applies the EQ predicate on the "api_endpoint" field.
func APIEndpointEQ(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEQ(FieldAPIEndpoint, v))
}

// APIEndpointNEQ applies the NEQ predicate on the "api_endpoint" field.
func APIEndpointNEQ(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNEQ(FieldAPIEndpoint, v))
}

// APIEndpointIn applies the In predicate on the "api_endpoint" field.
func APIEndpointIn(vs ...string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldIn(FieldAPIEndpoint, vs...))
}

// APIEndpointNotIn applies the NotIn predicate on the "api_endpoint" field.
func APIEndpointNotIn(vs ...string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldNotIn(FieldAPIEndpoint, vs...))
}

// APIEndpointGT applies the GT predicate on the "api_endpoint" field.
func APIEndpointGT(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGT(FieldAPIEndpoint, v))
}

// APIEndpointGTE applies the GTE predicate on the "api_endpoint" field.
func APIEndpointGTE(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldGTE(FieldAPIEndpoint, v))
}

// APIEndpointLT applies the LT predicate on the "api_endpoint" field.
func APIEndpointLT(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLT(FieldAPIEndpoint, v))
}

// APIEndpointLTE applies the LTE predicate on the "api_endpoint" field.
func APIEndpointLTE(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldLTE(FieldAPIEndpoint, v))
}

// APIEndpointContains applies the Contains predicate on the "api_endpoint" field.
func APIEndpointContains(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldContains(FieldAPIEndpoint, v))
}

// APIEndpointHasPrefix applies the HasPrefix predicate on the "api_endpoint" field.
func APIEndpointHasPrefix(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldHasPrefix(FieldAPIEndpoint, v))
}

// APIEndpointHasSuffix applies the HasSuffix predicate on the "api_endpoint" field.
func APIEndpointHasSuffix(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldHasSuffix(FieldAPIEndpoint, v))
}

// APIEndpointEqualFold applies the EqualFold predicate on the "api_endpoint" field.
func APIEndpointEqualFold(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldEqualFold(FieldAPIEndpoint, v))
}

// APIEndpointContainsFold applies the ContainsFold predicate on the "api_endpoint" field.
func APIEndpointContainsFold(v string) predicate.Lighthouse {
	return predicate.Lighthouse(sql.FieldContainsFold(FieldAPIEndpoint, v))
}

// HasHost applies the HasEdge predicate on the "host" edge.
func HasHost() predicate.Lighthouse {
	return predicate.Lighthouse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HostTable, HostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHostWith applies the HasEdge predicate on the "host" edge with a given conditions (other predicates).
func HasHostWith(preds ...predicate.Host) predicate.Lighthouse {
	return predicate.Lighthouse(func(s *sql.Selector) {
		step := newHostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Lighthouse) predicate.Lighthouse {
	return predicate.Lighthouse(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Lighthouse) predicate.Lighthouse {
	return predicate.Lighthouse(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Lighthouse) predicate.Lighthouse {
	return predicate.Lighthouse(sql.NotPredicates(p))
}
