// Code generated by ent, DO NOT EDIT.

package host

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sprisa/west/util/ipconv"
	"github.com/sprisa/west/westport/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldID, id))
}

// CreatedTime applies equality check predicate on the "created_time" field. It's identical to CreatedTimeEQ.
func CreatedTime(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCreatedTime, v))
}

// UpdatedTime applies equality check predicate on the "updated_time" field. It's identical to UpdatedTimeEQ.
func UpdatedTime(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldUpdatedTime, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldEQ(FieldIP, vc))
}

// CreatedTimeEQ applies the EQ predicate on the "created_time" field.
func CreatedTimeEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldCreatedTime, v))
}

// CreatedTimeNEQ applies the NEQ predicate on the "created_time" field.
func CreatedTimeNEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldCreatedTime, v))
}

// CreatedTimeIn applies the In predicate on the "created_time" field.
func CreatedTimeIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldCreatedTime, vs...))
}

// CreatedTimeNotIn applies the NotIn predicate on the "created_time" field.
func CreatedTimeNotIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldCreatedTime, vs...))
}

// CreatedTimeGT applies the GT predicate on the "created_time" field.
func CreatedTimeGT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldCreatedTime, v))
}

// CreatedTimeGTE applies the GTE predicate on the "created_time" field.
func CreatedTimeGTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldCreatedTime, v))
}

// CreatedTimeLT applies the LT predicate on the "created_time" field.
func CreatedTimeLT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldCreatedTime, v))
}

// CreatedTimeLTE applies the LTE predicate on the "created_time" field.
func CreatedTimeLTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldCreatedTime, v))
}

// UpdatedTimeEQ applies the EQ predicate on the "updated_time" field.
func UpdatedTimeEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldEQ(FieldUpdatedTime, v))
}

// UpdatedTimeNEQ applies the NEQ predicate on the "updated_time" field.
func UpdatedTimeNEQ(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldNEQ(FieldUpdatedTime, v))
}

// UpdatedTimeIn applies the In predicate on the "updated_time" field.
func UpdatedTimeIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldIn(FieldUpdatedTime, vs...))
}

// UpdatedTimeNotIn applies the NotIn predicate on the "updated_time" field.
func UpdatedTimeNotIn(vs ...time.Time) predicate.Host {
	return predicate.Host(sql.FieldNotIn(FieldUpdatedTime, vs...))
}

// UpdatedTimeGT applies the GT predicate on the "updated_time" field.
func UpdatedTimeGT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGT(FieldUpdatedTime, v))
}

// UpdatedTimeGTE applies the GTE predicate on the "updated_time" field.
func UpdatedTimeGTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldGTE(FieldUpdatedTime, v))
}

// UpdatedTimeLT applies the LT predicate on the "updated_time" field.
func UpdatedTimeLT(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLT(FieldUpdatedTime, v))
}

// UpdatedTimeLTE applies the LTE predicate on the "updated_time" field.
func UpdatedTimeLTE(v time.Time) predicate.Host {
	return predicate.Host(sql.FieldLTE(FieldUpdatedTime, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldEQ(FieldIP, vc))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldNEQ(FieldIP, vc))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...ipconv.IP) predicate.Host {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = uint32(vs[i])
	}
	return predicate.Host(sql.FieldIn(FieldIP, v...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...ipconv.IP) predicate.Host {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = uint32(vs[i])
	}
	return predicate.Host(sql.FieldNotIn(FieldIP, v...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldGT(FieldIP, vc))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldGTE(FieldIP, vc))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldLT(FieldIP, vc))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v ipconv.IP) predicate.Host {
	vc := uint32(v)
	return predicate.Host(sql.FieldLTE(FieldIP, vc))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Host) predicate.Host {
	return predicate.Host(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Host) predicate.Host {
	return predicate.Host(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Host) predicate.Host {
	return predicate.Host(sql.NotPredicates(p))
}
